### ISSUE TITLE
Apparent segfault

### ISSUE THREAD

**Issue by gdude2002** [jgeboski/bitlbee-steam#93]
I've been getting these and SIGBUS at random for a few days now. It started when I updated for the fix to #90.

![](http://vurl.com/PNg64)

```
➜  ~  tail /var/log/bitlbee.log -n50
User-Agent: Steam App / BitlBee / 1.3.0
Connection: Close
Accept: */*
Cookie: steamLogin=[REDACTED]%7C%7Coauth%3A[REDACTED]; forceMobile=1; mobileClient=BitlBee; sessionid=[REDACTED]
Host: api.steampowered.com


About to send HTTP request:
GET /ISteamUserOAuth/GetUserSummaries/v0001?steamids=[REDACTED]&access_token=[REDACTED] HTTP/1.1
User-Agent: Steam App / BitlBee / 1.3.0
Connection: Close
Accept: */*
Cookie: steamLogin=[REDACTED]%7C%7Coauth%3A[REDACTED]; forceMobile=1; mobileClient=BitlBee; sessionid=[REDACTED]
Host: api.steampowered.com


HTTP response headers:
HTTP/1.1 200 OK
Date: Sat, 22 Aug 2015 14:34:53 GMT
expires: Sat, 22 Aug 2015 14:34:53 GMT
Content-Type: application/json; charset=UTF-8
content-length: 19608

Finishing HTTP request with status: 200 OK
About to send HTTP request:
POST /ISteamWebUserPresenceOAuth/Poll/v0001 HTTP/1.1
User-Agent: Steam App / BitlBee / 1.3.0
Content-Length: 99
Connection: Keep-Alive
Accept: */*
Cookie: steamLogin=[REDACTED]%7C%7Coauth%3A[REDACTED]; forceMobile=1; mobileClient=BitlBee; sessionid=[REDACTED]
Host: api.steampowered.com
Content-Type: application/x-www-form-urlencoded

message=47&sectimeout=30&secidletime=0&access_token=[REDACTED]&umqid=[REDACTED]
HTTP response headers:
HTTP/1.1 200 OK
Date: Sat, 22 Aug 2015 14:34:54 GMT
expires: Sat, 22 Aug 2015 14:34:54 GMT
Content-Type: application/json; charset=UTF-8
content-length: 29

Finishing HTTP request with status: 200 OK
About to send HTTP request:
POST /ISteamWebUserPresenceOAuth/Logon/v0001 HTTP/1.1
User-Agent: Steam App / BitlBee / 1.3.0
Content-Length: 72
Connection: Close
Accept: */*
Cookie: steamLogin=[REDACTED]%7C%7Coauth%3A[REDACTED]; forceMobile=1; mobileClient=Bitl#  
```

As you can see, the file is truncated for some reason.

```
➜  ~  bitlbee -V
BitlBee 3.4.1
API version 030401
```

Any ideas?

---

EDIT: The apparent SIGBUS I was getting:

```
➜  ~  bitlbee -nDv
[1]    670 bus error (core dumped)  bitlbee -nDv
```

**Comment by gdude2002** [comment]
Alright, here's a bit more info.

```
[bitlbee-steam] POST Request (0x555555845ea0): https://api.steampowered.com:443/ISteamWebUserPresenceOAuth/Message/v0001
[bitlbee-steam]   User-Agent: Steam App / BitlBee / 1.3.0
[bitlbee-steam]   Content-Length: 181
[bitlbee-steam]   Connection: Close
[bitlbee-steam]   Accept: */*
[bitlbee-steam]   Cookie: steamLogin=[REDACTED]%7C%7Coauth%3A[REDACTED]; forceMobile=1; mobileClient=BitlBee; sessionid=[REDACTED]
[bitlbee-steam]   Host: api.steampowered.com
[bitlbee-steam]   Content-Type: application/x-www-form-urlencoded
[bitlbee-steam]
[bitlbee-steam]   steamid_dst=[REDACTED]&type=saytext&text=[REDACTED]&access_token=[REDACTED]&umqid=[REDACTED]
[bitlbee-steam] POST Response (0x555555845ea0): https://api.steampowered.com:443/ISteamWebUserPresenceOAuth/Message/v0001 (200 OK)
[bitlbee-steam]   HTTP/1.1 200 OK
[bitlbee-steam]   Date: Sun, 23 Aug 2015 10:02:36 GMT
[bitlbee-steam]   expires: Sun, 23 Aug 2015 10:02:36 GMT
[bitlbee-steam]   Content-Type: application/json; charset=UTF-8
[bitlbee-steam]   content-length: 29
[bitlbee-steam]
[bitlbee-steam]   {
[bitlbee-steam]         "error": "Not Logged On"
[bitlbee-steam]   }
[bitlbee-steam] Relogging on due to expired session
[bitlbee-steam] Request (0x555555846500) forcefully closed
[bitlbee-steam] POST Request (0x555555846500): https://api.steampowered.com:443/ISteamWebUserPresenceOAuth/Logon/v0001
[bitlbee-steam]   User-Agent: Steam App / BitlBee / 1.3.0
[bitlbee-steam]   Content-Length: 72
[bitlbee-steam]   Connection: Close
[bitlbee-steam]   Accept: */*
[bitlbee-steam]   Cookie: steamLogin=[REDACTED]%7C%7Coauth%3A[REDACTED]; forceMobile=1; mobileClient=BitlBee; sessionid=[REDACTED]
[bitlbee-steam]   Host: api.steampowered.com
[bitlbee-steam]   Content-Type: application/x-www-form-urlencoded
[bitlbee-steam]
[bitlbee-steam]   ui_mode=web&access_token=[REDACTED]&umqid=[REDACTED]
[bitlbee-steam] POST Response (0x555555846500): https://api.steampowered.com:443/ISteamWebUserPresenceOAuth/Logon/v0001 (Error while writing HTTP request)
[bitlbee-steam]   ** No header data **
[bitlbee-steam]
[bitlbee-steam]   ** No body data **

Program received signal SIGSEGV, Segmentation fault.
0x00005555558435e0 in ?? ()
#0  0x00005555558435e0 in ?? ()
#1  0x0000555555582b02 in ?? ()
#2  0x000055555557b30e in ?? ()
#3  0x00007ffff7610ce5 in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007ffff7611048 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007ffff761130a in g_main_loop_run () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#6  0x0000555555567711 in main ()
```

**Comment by gdude2002** [comment]
On the advice of @dequis I've reverted to using the debian repo for bitlbee (which has the debug symbols), and things seem to be more stable at this point, so I'm going to close the ticket.

If I find anything more on this, I'll reopen.
